Repository lightspeedwp/lsx-design, pull requests merged in 2023-11, with the labels that each got.

#55 Header designs with focus on Mobile
  assets/css/woocommerce.css
  includes/patterns/header/header-default.php
  parts/header-cta.html
  parts/header-dark.html
  parts/header.html
  parts/woo-header-dark.html
  parts/woo-header-light.html
  style.css
  theme.json
Labels: Needs Technical Feedback

#64 1.2.0 - WooCommerce Order Confirmation Template
  .DS_Store
  .gitignore
  .phpcs.xml.dist
  assets/css/woocommerce/order-confirmation-billing-wrapper.css
  assets/css/woocommerce/order-confirmation-totals.css
  includes/classes/class-core.php
  includes/classes/class-frontend.php
  includes/classes/woocommerce/class-assets.php
  includes/classes/woocommerce/class-woocommerce.php
  includes/patterns/featured/cover-2-col.php
  includes/patterns/featured/cover-banner-image.php
  includes/patterns/featured/general-hero-one-column.php
  includes/patterns/pages/page-about.php
  includes/patterns/pages/page-contact.php
  includes/patterns/pages/page-links.php
  includes/patterns/pages/page-team.php
  includes/patterns/pages/page-testimonials.php
  templates/order-confirmation.html
  theme.json
Labels: [Priority] Normal

#63 Remove of the "theme" attribute
  templates/archive.html
  templates/index.html
  templates/no-title.html
  templates/page.html
  templates/single.html
  templates/taxonomy-product_cat.html
  templates/woocommerce-blank.html
  templates/woocommerce-page.html
Labels: Needs Testing

#66 1.2.0 - Updates to the mobile menu
  .DS_Store
  .gitignore
  includes/classes/class-frontend.php
  style.css
Labels: [Priority] Critical

#68 1.2.0/wc product on sale block styling
  .DS_Store
  assets/.DS_Store
  assets/css/woocommerce.css
  assets/css/woocommerce/product-on-sale.css
  includes/classes/class-frontend.php
  includes/classes/woocommerce/class-assets.php
  style.css
  templates/taxonomy-product_cat.html
  templates/woocommerce-blank.html
  templates/woocommerce-page.html
Labels: [Priority] Normal

#69 Updated Footer files for Improved Mobile Design
  includes/patterns/footer/footer-default-contrast-background.php
  includes/patterns/footer/footer-default.php
  includes/patterns/footer/footer-mega-contrast-background.php
  includes/patterns/footer/footer-mega.php
  parts/footer-dark.html
  parts/footer.html
  style.css
Labels: [Status] Ready

#73 1.2.0 - editor and frontend differences
  assets/css/woocommerce.css
  assets/css/woocommerce/checkout-totals-block.css
  includes/classes/class-setup.php
  includes/classes/woocommerce/class-assets.php
Labels: [Priority] Normal
